services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001" # Map port 3001 in the container to 3001 on the host
    environment:
      - PORT=3001
    volumes:
      - ./shared:/app/shared # Mount shared directory
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "3002:3002" # Map port 3002 in the container to 3002 on the host
    environment:
      - PORT=3002
    volumes:
      - ./shared:/app/shared # Mount shared directory
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "3003:3003" # Map port 3003 in the container to 3003 on the host
    environment:
      - PORT=3003
    volumes:
      - ./shared:/app/shared # Mount shared directory
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000" # Map port 3000 in the container to 3000 on the host
    volumes:
      - ./shared:/app/shared # Mount shared directory
    networks:
      - microservices-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
